from typing import Protocol

from earlylock.domain.models import Agent, GameState


class ValorantGateway(Protocol):
    @property
    def player_name(self) -> str: ...

    @property
    def player_tag(self) -> str: ...

    def get_game_state(self) -> GameState: ...

    def get_pregame_id(self) -> str | None: ...

    def select_agent(self, match_id: str, agent: Agent) -> bool: ...

    def lock_agent(self, match_id: str, agent: Agent) -> bool: ...

    def close(self) -> None: ...
